var medicosIniciales = [
  {
    imagen: "../../assets/medicos/Dr. Atanasio Roberto Hasselbach.jpg",
    nombres: "Atanasio Roberto",
    apellidos: "Hasselbach",
    dni: 24524656356,
    telefono: 23452452,
    especialidad: "Neurología",
    matricula: "D-001",
  },
  {
    imagen: "../../assets/medicos/Dr. Eulogio Ramon Sarmiento.jpg",
    nombres: "Eulogio Ramón",
    apellidos: "Sarmiento",
    dni: 235262630,
    telefono: 235909809,
    especialidad: "Traumatología",
    matricula: "D-057",
  },
  {
    imagen: "../../assets/medicos/Dr. Francisco Braim.jpg",
    nombres: "Francisco",
    apellidos: "Braim",
    dni: 24540968098,
    telefono: 23450987,
    especialidad: "Odontología",
    matricula: "D-467",
  },
  {
    imagen: "../../assets/medicos/Dr. Guillermo Conti.jpg",
    nombres: "Guillermo",
    apellidos: "Conti",
    dni: 24356098234,
    telefono: 239874563,
    especialidad: "Neurología",
    matricula: "D-102",
  },
  {
    imagen: "../../assets/medicos/Dr. Horacio Barreto.jpg",
    nombres: "Horacio",
    apellidos: "Barreto",
    dni: 24490823456,
    telefono: 231234567,
    especialidad: "Cardiología",
    matricula: "D-103",
  },
  {
    imagen: "../../assets/medicos/Dr. Humberto Daniel Irrazabal.jpg",
    nombres: "Humberto Daniel",
    apellidos: "Irrazabal",
    dni: 24356789234,
    telefono: 236543210,
    especialidad: "Oftalmología",
    matricula: "D-104",
  },
  {
    imagen: "../../assets/medicos/Dr. Jesus Palacio.jpg",
    nombres: "Jesús",
    apellidos: "Palacio",
    dni: 24390876543,
    telefono: 231119876,
    especialidad: "Odontología",
    matricula: "D-105",
  },
  {
    imagen: "../../assets/medicos/Dr. José Martín Slopeer.jpg",
    nombres: "José Martín",
    apellidos: "Slopeer",
    dni: 24456782345,
    telefono: 232345678,
    especialidad: "Oftalmología",
    matricula: "D-106",
  },
  {
    imagen: "../../assets/medicos/Dr. Lorenzo Ferrarasi.jpg",
    nombres: "Lorenzo",
    apellidos: "Ferrarasi",
    dni: 24321098765,
    telefono: 239988776,
    especialidad: "Oftalmología",
    matricula: "D-107",
  },
  {
    imagen: "../../assets/medicos/Dr. Martin Ledesme.jpg",
    nombres: "Martín",
    apellidos: "Ledesme",
    dni: 24567892345,
    telefono: 238765432,
    especialidad: "Cardiología",
    matricula: "D-108",
  },
  {
    imagen: "../../assets/medicos/Dr. Matias Morales.jpg",
    nombres: "Matías",
    apellidos: "Morales",
    dni: 24509872345,
    telefono: 234112233,
    especialidad: "Ginecología",
    matricula: "D-109",
  },
  {
    imagen: "../../assets/medicos/Dra. Beatriz Gallardo.jpg",
    nombres: "Beatriz",
    apellidos: "Gallardo",
    dni: 24654321987,
    telefono: 236655443,
    especialidad: "Traumatología",
    matricula: "D-110",
  },
  {
    imagen: "../../assets/medicos/Dra. Lee Yamaguchi.jpg",
    nombres: "Lee",
    apellidos: "Yamaguchi",
    dni: 24765439821,
    telefono: 237788990,
    especialidad: "Odontología",
    matricula: "D-111",
  },
  {
    imagen: "../../assets/medicos/Dra. Paola Suarez.jpg",
    nombres: "Paola",
    apellidos: "Suarez",
    dni: 24678234509,
    telefono: 235665544,
    especialidad: "Traumatología",
    matricula: "D-112",
  },
  {
    imagen: "../../assets/medicos/Dra. Raquel Noemi Vera.jpg",
    nombres: "Raquel Noemí",
    apellidos: "Vera",
    dni: 24782345678,
    telefono: 239944332,
    especialidad: "Ginecología",
    matricula: "D-113",
  },
];
